{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "idp-demo.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "idp-demo.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ include "idp-demo.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
